### ISSUE TITLE
scrapy==2.2版本报错

### ISSUE THREAD

**Issue by chenpython** [Gerapy/GerapyPyppeteer#1]
> 
![QQ浏览器截图20200714103053](https://user-images.githubusercontent.com/45593480/87374126-35c7d180-c5bd-11ea-82c2-1dad0eb49c2e.png)

**Comment by Germey** [comment]
奇怪我这边也是 2.2 版本，没有出现问题，请问可以发下完整报错信息吗？

**Comment by Germey** [comment]
这个应该是 Python 3.8 的问题，切换到 3.7 应该就好了。

**Comment by Germey** [comment]
Closed due to no respond for a long time.
