### ISSUE TITLE
stub related to GERAPY_ENABLE_REQUEST_INTERCEPTION

### ISSUE THREAD

**Issue by Germey** [Gerapy/GerapyPyppeteer#24]
主要是因为 这个http://politics.people.com.cn/GB/99014/index.html页面会先302，然后跳到200，GERAPY_ENABLE_REQUEST_INTERCEPTION这个不设为false就会一直卡在里面[皱眉]我太菜了，不懂深层原因

如果 false 那这里他就会是302，一直请求重试，我目前用meta={'handle_httpstatus_list':[302]解决
![image](https://user-images.githubusercontent.com/8678661/115116507-67e2e580-9fcc-11eb-8856-1cbd5bcaf49f.png)

![image](https://user-images.githubusercontent.com/8678661/115116504-644f5e80-9fcc-11eb-8d5f-0491a288463e.png)

**Comment by JerryChenn07** [comment]
貌似 跟pyee版本有关，8.0.0-8.1.0 的会一直卡着

**Comment by kenyu01** [comment]
浏览器一直about：blank，什么情况

**Comment by Germey** [comment]
set GERAPY_ENABLE_REQUEST_INTERCEPTION to False default in 0.1.2
