### ISSUE TITLE
使用这个包可以打开网页 但是浏览器加载白屏

### ISSUE THREAD

**Issue by ggotost1990** [Gerapy/GerapyPyppeteer#27]
![image](https://user-images.githubusercontent.com/29170231/115496507-651e1400-a29c-11eb-981f-6d81ac62cdc5.png)
![image](https://user-images.githubusercontent.com/29170231/115496519-69e2c800-a29c-11eb-9047-0ee987a5b5c3.png)
![image](https://user-images.githubusercontent.com/29170231/115496532-6ea77c00-a29c-11eb-8357-ca3b415cf7da.png)

**Comment by kenyu01** [comment]
同求

**Comment by irhawks** [comment]
see #24

**Comment by Germey** [comment]
Should be fixed in 0.1.2, set GERAPY_ENABLE_REQUEST_INTERCEPTION default to False.
