### ISSUE TITLE
可能需要添加一些扩展功能

### ISSUE THREAD

**Issue by ayuge** [Gerapy/GerapyPyppeteer#4]
目前项目添加的 Pyppeteer 的功能已经能很好的解决大部分网站，减少了开发时间

1.但是一些反爬稍强的网站，还是需要一些 --enable-automation 或者反爬 js 的配置参数；

2.还有就是碰到下一页但是网址并不变化的网站，需要添加 page.click() 或相关的引导下一页功能的扩展参数。

比如在夜幕论坛看到的一个网址 aHR0cCUzQS8vMTI1LjM1LjYuODAlM0E4MTgxL2Z0YmFuLw== ，只需在源码中添加常见的反爬 js 就可以拿到第一页的数据，但是后几页在添加模拟点击后无效（页面未刷新），selenium 上还没试。

**Comment by ayuge** [comment]
又试了下，selenium + firefox 可以打开上面网站并获取所有页数据，selenium + chrome 和 pyppeteer 的 click 方法获取下一页数据无效，若你要添加 pyppeteer 的 click 方法的话可以参考下。

**Comment by Germey** [comment]
多谢建议，我设计下试试看

**Comment by Germey** [comment]
看样子这两个场景是不是都是因为检测了 webdriver 引起的，现在这个功能已经有了，可以试试看。

https://github.com/Gerapy/GerapyPyppeteer#pretend-as-real-browser
